version: '3'

services:
  vendorui:
    build:
      context: .
      dockerfile: AscendPortal/Dockerfile.CI
    environment:
      - OrderManagementQueryAPI=http://localhost:7380/api/v1.0
      - OrderFulfillmentQueryAPI=http://localhost:7580/api/v1.0
      - OrderManagementCommandAPI=http://localhost:7379/api/v1.0
      - OrderFulfillmentCommandAPI=http://localhost:7579/api/v1.0
      - VendorProfileQueryAPI=http://localhost:6480/api/v1.0
    ports:
      - "4100:4100"
